import './area'
import './button'
import './footer'
import './form'
import './header'
import './hide'
import './icon'
import './info'
import './input'
import './link'
import './logo'
import './modal'
import './redirect'
import './show'
import './stack'
import './tag'
import './text'
// import './validity'
