export const isPainted = Symbol.for('isPainted')
export const didPaintCallback = Symbol('didPaintCallback')
export const htmlCallback = Symbol('htmlCallback')
export const cssCallback = Symbol('cssCallback')
export const willPaintCallback = Symbol('willPaintCallback')
